import { City, Review, Cafe } from "./types";

export const mockCities: City[] = [
  {
    id: "jeju",
    name: "제주시",
    nameEn: "Jeju City",
    regionDetail: "제주특별자치도",
    description: "아름다운 자연과 카페 문화가 발달한 디지털 노마드의 성지",
    images: [
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
      "https://images.unsplash.com/photo-1590059111219-bd2c1f29f2cb?w=800",
      "https://images.unsplash.com/photo-1578217115839-dc1a82d6160b?w=800",
    ],
    overallRating: 4.5,
    costOfLiving: 1800000,
    internetSpeed: 120,
    safetyScore: 4.8,
    currentWeather: {
      temp: 20,
      feelsLike: 18,
      condition: "맑음",
    },
    airQuality: {
      aqi: 15,
      level: "좋음",
    },
    metrics: {
      cafeCount: 150,
      coworkingCount: 12,
      transportScore: 3.5,
      cultureScore: 4.2,
    },
    reviewCount: 245,
    bookmarkCount: 892,
    rank: 1,
    tags: ["해변", "카페", "자연", "관광"],
    likes: 456,
    dislikes: 12,
    budgetRange: "200만원 이상",
    region: "제주도",
    environments: ["자연친화", "카페작업"],
    bestSeason: "봄",
  },
  {
    id: "gangneung",
    name: "강릉",
    nameEn: "Gangneung",
    regionDetail: "강원도",
    description: "바다와 카페 거리가 어우러진 힐링 도시",
    images: [
      "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=800",
      "https://images.unsplash.com/photo-1570284613060-766c33f6f2e5?w=800",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    ],
    overallRating: 4.3,
    costOfLiving: 1200000,
    internetSpeed: 95,
    safetyScore: 4.7,
    currentWeather: {
      temp: 18,
      feelsLike: 16,
      condition: "구름조금",
    },
    airQuality: {
      aqi: 22,
      level: "좋음",
    },
    metrics: {
      cafeCount: 89,
      coworkingCount: 5,
      transportScore: 3.2,
      cultureScore: 4.0,
    },
    reviewCount: 189,
    bookmarkCount: 567,
    rank: 2,
    tags: ["해변", "카페", "조용함"],
    likes: 389,
    dislikes: 15,
    budgetRange: "100~200만원",
    region: "강원도",
    environments: ["자연친화", "카페작업"],
    bestSeason: "여름",
  },
  {
    id: "busan",
    name: "부산 해운대",
    nameEn: "Busan Haeundae",
    regionDetail: "부산광역시",
    description: "대도시의 편의성과 해변의 여유를 동시에",
    images: [
      "https://images.unsplash.com/photo-1590841609987-4ac211afdde1?w=800",
      "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=800",
      "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800",
    ],
    overallRating: 4.4,
    costOfLiving: 1500000,
    internetSpeed: 110,
    safetyScore: 4.5,
    currentWeather: {
      temp: 22,
      feelsLike: 21,
      condition: "맑음",
    },
    airQuality: {
      aqi: 35,
      level: "보통",
    },
    metrics: {
      cafeCount: 200,
      coworkingCount: 18,
      transportScore: 4.5,
      cultureScore: 4.3,
    },
    reviewCount: 312,
    bookmarkCount: 721,
    rank: 3,
    tags: ["해변", "도심", "대도시"],
    likes: 421,
    dislikes: 18,
    budgetRange: "100~200만원",
    region: "경상도",
    environments: ["도심선호", "카페작업"],
    bestSeason: "여름",
  },
  {
    id: "jeonju",
    name: "전주",
    nameEn: "Jeonju",
    regionDetail: "전라북도",
    description: "전통과 현대가 공존하는 저렴한 생활비의 문화 도시",
    images: [
      "https://images.unsplash.com/photo-1583225214464-9296029427aa?w=800",
      "https://images.unsplash.com/photo-1590959651373-a3db0f38a961?w=800",
      "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=800",
    ],
    overallRating: 4.2,
    costOfLiving: 900000,
    internetSpeed: 85,
    safetyScore: 4.6,
    currentWeather: {
      temp: 19,
      feelsLike: 18,
      condition: "흐림",
    },
    airQuality: {
      aqi: 28,
      level: "좋음",
    },
    metrics: {
      cafeCount: 75,
      coworkingCount: 4,
      transportScore: 3.8,
      cultureScore: 4.7,
    },
    reviewCount: 156,
    bookmarkCount: 423,
    rank: 4,
    tags: ["전통", "가성비", "문화"],
    likes: 267,
    dislikes: 23,
    budgetRange: "100만원 이하",
    region: "전라도",
    environments: ["자연친화", "카페작업"],
    bestSeason: "가을",
  },
  {
    id: "seoul-gangnam",
    name: "서울 강남",
    nameEn: "Seoul Gangnam",
    regionDetail: "서울특별시",
    description: "최고의 인프라와 비즈니스 환경을 갖춘 대한민국 중심지",
    images: [
      "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=800",
      "https://images.unsplash.com/photo-1562818255-d7c5f56dddb5?w=800",
      "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800",
    ],
    overallRating: 4.6,
    costOfLiving: 2500000,
    internetSpeed: 150,
    safetyScore: 4.4,
    currentWeather: {
      temp: 17,
      feelsLike: 15,
      condition: "맑음",
    },
    airQuality: {
      aqi: 45,
      level: "보통",
    },
    metrics: {
      cafeCount: 350,
      coworkingCount: 45,
      transportScore: 5.0,
      cultureScore: 4.8,
    },
    reviewCount: 428,
    bookmarkCount: 1234,
    rank: 5,
    tags: ["도심", "비즈니스", "최고급"],
    likes: 503,
    dislikes: 45,
    budgetRange: "200만원 이상",
    region: "수도권",
    environments: ["도심선호", "코워킹 필수"],
    bestSeason: "봄",
  },
  {
    id: "sokcho",
    name: "속초",
    nameEn: "Sokcho",
    regionDetail: "강원도",
    description: "설악산과 바다를 동시에 즐길 수 있는 자연 친화 도시",
    images: [
      "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=800",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800",
    ],
    overallRating: 4.0,
    costOfLiving: 1000000,
    internetSpeed: 80,
    safetyScore: 4.8,
    currentWeather: {
      temp: 16,
      feelsLike: 14,
      condition: "맑음",
    },
    airQuality: {
      aqi: 12,
      level: "좋음",
    },
    metrics: {
      cafeCount: 45,
      coworkingCount: 2,
      transportScore: 2.8,
      cultureScore: 3.5,
    },
    reviewCount: 98,
    bookmarkCount: 234,
    rank: 6,
    tags: ["산", "해변", "자연"],
    likes: 178,
    dislikes: 28,
    budgetRange: "100만원 이하",
    region: "강원도",
    environments: ["자연친화"],
    bestSeason: "여름",
  },
  {
    id: "chuncheon",
    name: "춘천",
    nameEn: "Chuncheon",
    regionDetail: "강원도",
    description: "서울 근교의 저렴하고 조용한 호반 도시",
    images: [
      "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=800",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      "https://images.unsplash.com/photo-1433838552652-f9a46b332c40?w=800",
    ],
    overallRating: 3.9,
    costOfLiving: 950000,
    internetSpeed: 90,
    safetyScore: 4.7,
    currentWeather: {
      temp: 15,
      feelsLike: 13,
      condition: "구름많음",
    },
    airQuality: {
      aqi: 25,
      level: "좋음",
    },
    metrics: {
      cafeCount: 60,
      coworkingCount: 3,
      transportScore: 3.5,
      cultureScore: 3.7,
    },
    reviewCount: 87,
    bookmarkCount: 189,
    rank: 7,
    tags: ["호수", "서울근교", "조용함"],
    likes: 145,
    dislikes: 32,
    budgetRange: "100만원 이하",
    region: "강원도",
    environments: ["자연친화", "카페작업"],
    bestSeason: "봄",
  },
  {
    id: "daegu",
    name: "대구",
    nameEn: "Daegu",
    regionDetail: "대구광역시",
    description: "적당한 생활비와 도시 인프라를 갖춘 균형잡힌 도시",
    images: [
      "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=800",
      "https://images.unsplash.com/photo-1562818255-d7c5f56dddb5?w=800",
      "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800",
    ],
    overallRating: 4.1,
    costOfLiving: 1100000,
    internetSpeed: 100,
    safetyScore: 4.5,
    currentWeather: {
      temp: 21,
      feelsLike: 20,
      condition: "맑음",
    },
    airQuality: {
      aqi: 38,
      level: "보통",
    },
    metrics: {
      cafeCount: 120,
      coworkingCount: 10,
      transportScore: 4.2,
      cultureScore: 4.0,
    },
    reviewCount: 145,
    bookmarkCount: 312,
    rank: 8,
    tags: ["도심", "가성비", "균형"],
    likes: 234,
    dislikes: 35,
    budgetRange: "100~200만원",
    region: "경상도",
    environments: ["도심선호"],
    bestSeason: "가을",
  },
  {
    id: "yeosu",
    name: "여수",
    nameEn: "Yeosu",
    regionDetail: "전라남도",
    description: "아름다운 해안 경관과 여유로운 분위기의 항구 도시",
    images: [
      "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=800",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
    ],
    overallRating: 4.2,
    costOfLiving: 1050000,
    internetSpeed: 75,
    safetyScore: 4.6,
    currentWeather: {
      temp: 20,
      feelsLike: 19,
      condition: "맑음",
    },
    airQuality: {
      aqi: 20,
      level: "좋음",
    },
    metrics: {
      cafeCount: 55,
      coworkingCount: 3,
      transportScore: 3.0,
      cultureScore: 3.8,
    },
    reviewCount: 112,
    bookmarkCount: 267,
    rank: 9,
    tags: ["해변", "경관", "여유"],
    likes: 198,
    dislikes: 41,
    budgetRange: "100~200만원",
    region: "전라도",
    environments: ["자연친화"],
    bestSeason: "가을",
  },
  {
    id: "gyeongju",
    name: "경주",
    nameEn: "Gyeongju",
    regionDetail: "경상북도",
    description: "천년 고도의 역사와 문화가 살아있는 관광 도시",
    images: [
      "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=800",
      "https://images.unsplash.com/photo-1583225214464-9296029427aa?w=800",
      "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800",
    ],
    overallRating: 3.8,
    costOfLiving: 850000,
    internetSpeed: 70,
    safetyScore: 4.8,
    currentWeather: {
      temp: 18,
      feelsLike: 17,
      condition: "구름조금",
    },
    airQuality: {
      aqi: 30,
      level: "좋음",
    },
    metrics: {
      cafeCount: 42,
      coworkingCount: 2,
      transportScore: 3.2,
      cultureScore: 5.0,
    },
    reviewCount: 76,
    bookmarkCount: 178,
    rank: 10,
    tags: ["역사", "전통", "관광"],
    likes: 123,
    dislikes: 38,
    budgetRange: "100만원 이하",
    region: "경상도",
    environments: ["자연친화"],
    bestSeason: "봄",
  },
];

export const mockReviews: Review[] = [
  {
    id: "review-1",
    userId: "user-1",
    userName: "김노마드",
    userAvatar: "https://i.pravatar.cc/150?img=1",
    cityId: "jeju",
    cityName: "제주시",
    overallRating: 5.0,
    ratings: {
      costSatisfaction: 4.0,
      internetQuality: 5.0,
      workEnvironment: 5.0,
      amenities: 4.5,
      community: 4.5,
      transport: 3.5,
      nature: 5.0,
    },
    content: "제주에서 3개월 살았는데 정말 최고였어요! 카페도 많고 바다도 가깝고... 다만 생활비가 조금 높은 편이긴 해요. 그래도 만족스럽습니다 👍",
    images: [
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
      "https://images.unsplash.com/photo-1590059111219-bd2c1f29f2cb?w=400",
    ],
    stayDuration: "3개월",
    occupation: "개발자",
    recommendedSeason: ["봄", "가을"],
    helpfulCount: 24,
    commentCount: 3,
    createdAt: "2시간 전",
    isVerified: true,
  },
  {
    id: "review-2",
    userId: "user-2",
    userName: "박개발자",
    userAvatar: "https://i.pravatar.cc/150?img=2",
    cityId: "gangneung",
    cityName: "강릉",
    overallRating: 4.0,
    ratings: {
      costSatisfaction: 4.5,
      internetQuality: 4.0,
      workEnvironment: 4.5,
      amenities: 3.5,
      community: 3.5,
      transport: 3.0,
      nature: 4.5,
    },
    content: "조용하고 카페 분위기가 너무 좋아요. 작업하기 딱입니다!",
    images: [],
    stayDuration: "1개월",
    occupation: "개발자",
    recommendedSeason: ["여름"],
    helpfulCount: 18,
    commentCount: 2,
    createdAt: "5시간 전",
    isVerified: true,
  },
  {
    id: "review-3",
    userId: "user-3",
    userName: "이디자이너",
    userAvatar: "https://i.pravatar.cc/150?img=3",
    cityId: "busan",
    cityName: "부산 해운대",
    overallRating: 5.0,
    ratings: {
      costSatisfaction: 4.0,
      internetQuality: 5.0,
      workEnvironment: 4.5,
      amenities: 5.0,
      community: 4.5,
      transport: 5.0,
      nature: 4.0,
    },
    content: "바다 보면서 일하니까 힐링되네요 ㅎㅎ 인터넷도 빠르고 좋습니다!",
    images: [
      "https://images.unsplash.com/photo-1598965675045-8f47f6db897a?w=400",
    ],
    stayDuration: "2개월",
    occupation: "디자이너",
    recommendedSeason: ["여름", "가을"],
    helpfulCount: 31,
    commentCount: 5,
    createdAt: "1일 전",
    isVerified: true,
  },
  {
    id: "review-4",
    userId: "user-4",
    userName: "최작가",
    userAvatar: "https://i.pravatar.cc/150?img=4",
    cityId: "jeonju",
    cityName: "전주",
    overallRating: 4.5,
    ratings: {
      costSatisfaction: 5.0,
      internetQuality: 3.5,
      workEnvironment: 4.0,
      amenities: 4.0,
      community: 4.5,
      transport: 4.0,
      nature: 3.5,
    },
    content: "생활비가 정말 저렴해서 좋아요! 한옥마을도 산책하기 좋고 전통 느낌이 좋습니다.",
    images: [],
    stayDuration: "6개월",
    occupation: "작가",
    recommendedSeason: ["봄", "가을"],
    helpfulCount: 15,
    commentCount: 1,
    createdAt: "2일 전",
    isVerified: true,
  },
  {
    id: "review-5",
    userId: "user-5",
    userName: "정마케터",
    userAvatar: "https://i.pravatar.cc/150?img=5",
    cityId: "seoul-gangnam",
    cityName: "서울 강남",
    overallRating: 4.5,
    ratings: {
      costSatisfaction: 3.0,
      internetQuality: 5.0,
      workEnvironment: 5.0,
      amenities: 5.0,
      community: 5.0,
      transport: 5.0,
      nature: 3.0,
    },
    content: "인프라 최고! 밋업도 많고 네트워킹하기 좋습니다. 다만 생활비가 많이 들어요.",
    images: [],
    stayDuration: "1년",
    occupation: "마케터",
    recommendedSeason: ["사계절"],
    helpfulCount: 42,
    commentCount: 8,
    createdAt: "3일 전",
    isVerified: true,
  },
];

export const mockCafes: Cafe[] = [
  {
    id: "cafe-1",
    cityId: "jeju",
    name: "바다뷰 카페",
    address: "제주시 연동 123-45",
    wifiSpeed: 150,
    hasPowerOutlet: true,
    noiseLevel: 2.5,
    priceRange: 3,
    rating: 4.8,
    images: ["https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400"],
  },
  {
    id: "cafe-2",
    cityId: "jeju",
    name: "제주 코워킹 스페이스",
    address: "제주시 노형동 234-56",
    wifiSpeed: 200,
    hasPowerOutlet: true,
    noiseLevel: 1.5,
    priceRange: 2,
    rating: 4.9,
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?w=400"],
  },
  {
    id: "cafe-3",
    cityId: "gangneung",
    name: "강릉 커피거리 카페",
    address: "강릉시 안목동 345-67",
    wifiSpeed: 100,
    hasPowerOutlet: true,
    noiseLevel: 3.0,
    priceRange: 2,
    rating: 4.5,
    images: ["https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400"],
  },
  {
    id: "cafe-4",
    cityId: "busan",
    name: "해운대 비치 카페",
    address: "부산시 해운대구 해운대해변로 456-78",
    wifiSpeed: 120,
    hasPowerOutlet: true,
    noiseLevel: 3.5,
    priceRange: 3,
    rating: 4.6,
    images: ["https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400"],
  },
];

// Helper function to get city by ID
export function getCityById(id: string): City | undefined {
  return mockCities.find((city) => city.id === id);
}

// Helper function to get reviews by city ID
export function getReviewsByCityId(cityId: string): Review[] {
  return mockReviews.filter((review) => review.cityId === cityId);
}

// Helper function to get cafes by city ID
export function getCafesByCityId(cityId: string): Cafe[] {
  return mockCafes.filter((cafe) => cafe.cityId === cityId);
}

// Helper function to get top cities
export function getTopCities(limit: number = 10): City[] {
  return mockCities
    .sort((a, b) => (b.rank || 0) - (a.rank || 0))
    .slice(0, limit);
}
